ignore:
  - "csaransh-pp/third_party/*" # ignoring catch and disjoint-set
  - "csaransh-pp/src/main.cpp"  # ignoring for only boilerplate 
  - "csaransh-pp/src/printJson.cpp" # ignoring for only printing boilerplate 
  - "csaransh-pp/include/printJson.hpp" # ignoring for only printing boilerplate 
  - "csaransh-pp/include/printJson.hpp" # ignoring for only printing boilerplate 
